///create_previewer_anchors(previewer, system);

var v = argument0, sys = argument1;
var t;
t=0;
t[0] = K_System_FindObject(sys, "Earth");
t[1] = 0;
ds_list_add(v.position, t);
t=0;
t[0] = K_System_GetMainStar(sys);
t[1] = room_speed*7;
ds_list_add(v.position, t);
t=0;
t[0] = K_System_FindObject(sys, "Jupiter");
t[1] = room_speed*11;
ds_list_add(v.position, t);




t=0;
t[0] = 0.065;
t[1] = 0;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 9*power(10,-4);
t[1] = room_speed*2;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 1*power(10,-5);
t[1] = room_speed*4;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = power(10,-6);
t[1] = room_speed*5;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 4*power(10,-7);
t[1] = room_speed*6;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 4*power(10,-8);
t[1] = room_speed*7;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 3.5*power(10,-9);
t[1] = room_speed*9;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 3.5*power(10,-9);
t[1] = room_speed*10;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = power(10,-8);
t[1] = room_speed*11;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = power(10,-7);
t[1] = room_speed*12;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = power(10,-6);
t[1] = room_speed*13;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 2*power(10,-5);
t[1] = room_speed*14.2;
ds_list_add(v.zoom_level, t);
t=0;
t[0] = 2*power(10,-4);
t[1] = room_speed*15;
ds_list_add(v.zoom_level, t);


t=0;
t[0] = 5*power(10,4)/room_speed;
t[1] = 0;
ds_list_add(v.time_step, t);
t=0;
t[0] = power(10,6)/room_speed;
t[1] = room_speed*6;
ds_list_add(v.time_step, t);
t=0;
t[0] = power(10,8)/room_speed;
t[1] = room_speed*7;
ds_list_add(v.time_step, t);
t=0;
t[0] = power(10,10)/room_speed;
t[1] = room_speed*9;
ds_list_add(v.time_step, t);
t=0;
t[0] = power(10,8)/room_speed;
t[1] = room_speed*11;
ds_list_add(v.time_step, t);
t=0;
t[0] = power(10,5)/room_speed;
t[1] = room_speed*14;
ds_list_add(v.time_step, t);